###

POST https://american-british-translator.freecodecamp.rocks/api/translate HTTP/1.1
Content-Type: application/json

{ "text": "Mangoes are my favorite fruit", "locale": "american-to-british" }

###

POST http://localhost:3000/api/translate HTTP/1.1
Content-Type: application/json

{
    "text": "Mangoes are my favorite fruit",
    "locale": "british-to-american"
}
